// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

//go:generate mockgen -destination ./user_mock.go -package user -source $GOFILE

package user

import (
	"context"

	"gozero_micro_food/usermanage/rpc/user/pro/user"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	RegisterRequest = user.RegisterRequest
	UserinfoRequest = user.UserinfoRequest
	Response        = user.Response
	LoginRequest    = user.LoginRequest

	User interface {
		Login(ctx context.Context, in *LoginRequest) (*Response, error)
		Register(ctx context.Context, in *RegisterRequest) (*Response, error)
		Userinfo(ctx context.Context, in *UserinfoRequest) (*Response, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Login(ctx context.Context, in *LoginRequest) (*Response, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in)
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterRequest) (*Response, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in)
}

func (m *defaultUser) Userinfo(ctx context.Context, in *UserinfoRequest) (*Response, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Userinfo(ctx, in)
}
